// File generated by FlutterFire CLI.
// Ini adalah contoh file, Anda perlu menjalankan 'flutterfire configure' untuk membuat file ini
// dengan kredensial Firebase Anda yang sebenarnya.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] untuk digunakan dengan aplikasi Firebase Anda.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions belum dikonfigurasi untuk platform windows - '
          'gunakan flutterfire configure untuk menghasilkan file platform-spesifik.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions belum dikonfigurasi untuk platform linux - '
          'gunakan flutterfire configure untuk menghasilkan file platform-spesifik.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions tidak tersedia untuk platform ini.',
        );
    }
  }

  // Isi bagian ini dengan konfigurasi Firebase Anda dari flutterfire configure
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBni0ry2B-L9E0At8QbUe5jnIxK0f5eYr8',
    appId: '1:954315198878:android:ea610b827d199593dc068f',
    messagingSenderId: '954315198878',
    projectId: 'chat-app-project-5a95d',
    authDomain: 'YOUR_AUTH_DOMAIN',
    storageBucket: 'chat-app-project-5a95d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBni0ry2B-L9E0At8QbUe5jnIxK0f5eYr8',
    appId: '1:954315198878:android:ea610b827d199593dc068f',
    messagingSenderId: '954315198878',
    projectId: 'chat-app-project-5a95d',
    storageBucket: 'chat-app-project-5a95d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBni0ry2B-L9E0At8QbUe5jnIxK0f5eYr8',
    appId: '1:954315198878:android:ea610b827d199593dc068f',
    messagingSenderId: '954315198878',
    projectId: 'chat-app-project-5a95d',
    storageBucket: 'chat-app-project-5a95d.firebasestorage.app',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBni0ry2B-L9E0At8QbUe5jnIxK0f5eYr8',
    appId: '1:954315198878:android:ea610b827d199593dc068f',
    messagingSenderId: '954315198878',
    projectId: 'chat-app-project-5a95d',
    storageBucket: 'chat-app-project-5a95d.firebasestorage.app',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );
}